export const HeadCellsGitJira = [
    {
        id: "issueType",
        label: "T",
        numeric: false,
        disablePadding: true,
        width: "30px",
        minWidth: "30px",
    },
    {
        id: "task",
        label: "Номер",
        numeric: false,
        disablePadding: true,
        width: "112px",
        minWidth: "112px",
    },
    {
        id: "statusTo",
        label: "Cтатус",
        numeric: false,
        disablePadding: true,
        width: "50px",
        minWidth: "50px",
    },
    {
        id: "issueName",
        label: "Задача",
        numeric: false,
        disablePadding: true,
        width: "240px",
        minWidth: "240px",
    },
    {
        id: "project",
        numeric: false,
        disablePadding: true,
        width: "75px",
        minWidth: "75px",
        label: "Проект",
    },
    {
        id: "firstContributorName",
        numeric: false,
        disablePadding: true,
        width: "175px",
        minWidth: "175px",
        label: "Участники",
    },
];
