<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiffMatchPatch" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.32" />
    <PackageReference Include="NEST" Version="7.10.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Analyzer.Common.Infrastructure\Analyzer.Common.Infrastructure.csproj" />
  </ItemGroup>

</Project>
