import { ProjectLinks } from "./ProjectLinks.model";
import { ProjectNamespace } from "./ProjectNamespace.model";
import { ProjectPermissions } from "./ProjectPermissions.model";

export interface ProjectModel {
    id: number;
    description: string;
    name: string;
    name_with_namespace: string;
    path: string;
    path_with_namespace: string;
    created_at: string;
    default_branch: string;
    tag_list: string[];
    ssh_url_to_repo: string;
    http_url_to_repo: string;
    web_url: string;
    readme_url: string;
    avatar_url?: string | null;
    star_count: number;
    forks_count: number;
    last_activity_at: string;
    namespace: ProjectNamespace;
    _links: ProjectLinks;
    archived: boolean;
    visibility: string;
    resolve_outdated_diff_discussions?: boolean;
    container_registry_enabled: boolean;
    issues_enabled: boolean;
    merge_requests_enabled: boolean;
    wiki_enabled: boolean;
    jobs_enabled: boolean;
    snippets_enabled: boolean;
    shared_runners_enabled: boolean;
    lfs_enabled: boolean;
    creator_id: number;
    import_status: string;
    open_issues_count: number;
    public_jobs: boolean;
    ci_config_path?: string | null;
    shared_with_groups: any[];
    only_allow_merge_if_pipeline_succeeds: boolean;
    request_access_enabled: boolean;
    only_allow_merge_if_all_discussions_are_resolved: boolean;
    printing_merge_request_link_enabled: boolean;
    merge_method: string;
    external_authorization_classification_label?: string | null;
    permissions: ProjectPermissions;
}
